services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8000}:8000"
    environment:
      - SUPABASE_DB_URL=${SUPABASE_DB_URL}
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - HOST=${HOST:-127.0.0.1}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:8080}
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:16-alpine
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
