-- AlterTable
ALTER TABLE "AI_Request" ADD COLUMN     "init_upload_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "last_upload_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "upload_count" INTEGER NOT NULL DEFAULT 0;
